// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrVzVGXXMNHqlNHL9agwzeXNSs1emxqSQ',
    appId: '1:466784854958:web:fcf343e2c67511a82c1e3f',
    messagingSenderId: '466784854958',
    projectId: 'travely-mbti',
    authDomain: 'travely-mbti.firebaseapp.com',
    storageBucket: 'travely-mbti.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ7PGFkLR8Q4eeou6qESz2kVcpGg0xM7k',
    appId: '1:466784854958:android:021e7e83a77e5ff02c1e3f',
    messagingSenderId: '466784854958',
    projectId: 'travely-mbti',
    storageBucket: 'travely-mbti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQMAhdFNmTdbxrHY-W1krT-B2b_KjY3KA',
    appId: '1:466784854958:ios:ca6e33675fa112f12c1e3f',
    messagingSenderId: '466784854958',
    projectId: 'travely-mbti',
    storageBucket: 'travely-mbti.firebasestorage.app',
    iosBundleId: 'com.example.travely',
  );
}
